### ISSUE TITLE
No SSH keys for user 'root' found. Script will abort!

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/t-pot-autoinstall#1]
could you introduce me how can slove this problems 
in know i need ssh keys but i dont know where to put keys on OS.

thanks indeed.

**Comment by schmalle** [comment]
I am not sure, if I understand the problem. If you setup an ubuntu system, you must have the root pw. Have you tried to sudo -i and then start the install ?

Below some general links for ubuntu

http://askubuntu.com/questions/115151/how-to-setup-passwordless-ssh-access-for-root-user
http://superuser.com/questions/614438/ssh-keys-for-root-user-and-normal-user-in-ubuntu

Hope this helps.

Best regards

Markus

**Comment by jjjan** [comment]
Make sure the SSH login for your normal user is working!

Which user do you usually work with? This script is invoked by root, but what is your normal username?
Enter username: root

Checking prerequisites...
### No SSH keys for user 'root' found. Script will abort!

it's not work am i need generate ssh key for root?

**Comment by dev-t-sec** [comment]
The script assumes, you e.g. start with a normal user and then sudo.
E.g. create a user "demo".
Create ssh keys for this user.
sudo -i
When asked, enter "demo".

This should work :)

**Comment by laurentl1** [comment]
Hi
same problem here, 
I did : 

adduser 
created user named demo

then once logged with this user : 

ssh-keygen -t rsa -b 2048
(default location)

so I have :  id_rsa and id_rsa.pub files in /demo/.ssh folder

then I've got the error message : 

##########################################################
# T-Pot 17.10 install script                             #
# for Ubuntu server 16.04.0x, x64                        #
##########################################################
Make sure the key-based SSH login for your normal user is working!

Which user do you usually work with?
This script is invoked by root, but what is your normal username?
Enter username: demo

Checking prerequisites...
### No SSH key for user 'demo' found in /home/demo/.ssh/authorized_keys.\n ### Script will abort!

**Comment by laurentl1** [comment]
ok I've found the solution so from ssh folder

made : 
touch authorized_keys
chmod 600 authorized_keys
cat id_rsa.pub >> authorized_keys

**Comment by vorband** [comment]
Authorized keys are stored in /home/<username>/.ssh/authorized_keys 
This is where the autoinstaller script is trying to locate them and aborts if the file does not contain an ssh pub key. 

You need to be able to login to your machine using the ssh key before you start the script.

**Comment by laurentl1** [comment]
yes thank you an congratz for the job :)

**Comment by laurentl1** [comment]
after the complete installation and reboot I can log to the interface but nothing works except the cli console, I can't do a sudo with my user, does it should be sudoer ?

**Comment by vorband** [comment]
the autoinstaller script is intended to transform a standard ubuntu 16.04 installation into t-pot. The first user you add during a ubuntu base install is sudo enabled. This is a prerequisite and assumption for the script. 

Did you install on a clean ubuntu 16.04 installation? Or a cloud instance? Which user is the normal "sudo-enabled" user? Do you meet the [system requirements](https://github.com/dtag-dev-sec/tpotce#requirements)? Did you make any config changes? Did you / your provider change the standard apt sources?  

Debugging this is very time consuming. I recommend you start all over. Setup an Ubuntu 16.04 machine with the right [system requirements](https://github.com/dtag-dev-sec/tpotce#requirements). During install, set your normal username (not root!) and password, enable ssh, add your ssh key to the /home/yourusername/.ssh/authorized_keys, make sure the login works as normal "non-root" user via ssh and without password prompt. Make sure the user is sudo enabled, clone the t-pot-autoinstaller repo, switch user (su) to root, execute the autoinstall script and give your username (not root!) when prompted. 

There are multiple reasons why the services did not start. Start by searching the t-pot issue list: 
https://github.com/dtag-dev-sec/tpotce/issues?q=is%3Aissue+is%3Aclosed
If you did not find any solution, open an issue here and supply the appropriate infos.  
https://github.com/dtag-dev-sec/tpotce/issues

**Comment by ColeHou** [comment]
> ok I've found the solution so from ssh folder
> 
> made :
> touch authorized_keys
> chmod 600 authorized_keys
> cat id_rsa.pub >> authorized_keys

tks
