### ISSUE TITLE
SSHD fails

### ISSUE THREAD

**Issue by jdjames1** [dtag-dev-sec/t-pot-autoinstall#14]
It looks like the patch to SSHD is messing up the format of sshd (see below)

# CLOUD_IMG: This file was created/modified by the Cloud Image build process
ClientAliveInterval 120Match address 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    PasswordAuthentication yes

due to this, sshd fails to start

Apr 26 17:06:17 switchfeature systemd[1]: Starting OpenBSD Secure Shell server...
Apr 26 17:06:17 switchfeature sshd[38383]: /etc/ssh/sshd_config line 90: invalid time value.
Apr 26 17:06:17 switchfeature systemd[1]: ssh.service: Main process exited, code=exited, status=255/n/a
Apr 26 17:06:17 switchfeature systemd[1]: Failed to start OpenBSD Secure Shell server.
Apr 26 17:06:17 switchfeature systemd[1]: ssh.service: Unit entered failed state.
Apr 26 17:06:17 switchfeature systemd[1]: ssh.service: Failed with result 'exit-code'.

**Comment by t3chn0m4g3** [comment]
Thank you, should be fixed now. Please try again by cloning from master.

**Comment by t3chn0m4g3** [comment]
Seems to work, closing for now.
