### ISSUE TITLE
Keyboard Type Selection Issue

### ISSUE THREAD

**Issue by masifpak** [dtag-dev-sec/t-pot-autoinstall#15]
While installation, script ask for keyboard type and require multiple key types which is irritating. Can we made a change seed file or some where so that we can avoid this step also.

**Comment by t3chn0m4g3** [comment]
No, this is intentionally since a seed file would require to pre-select a keyboard type.

**Comment by t3chn0m4g3** [comment]
However you can modify the [preseed](https://github.com/dtag-dev-sec/tpotce/blob/master/preseed/tpot.seed) file to your needs before building the ISO.

**Comment by masifpak** [comment]
In tpot.seed file i just changed in keyboard section as shown below and comment remaining two lines. Now It skip keuboard setting step.

> d-i keyboard-configuration/layoutcode string us

**Comment by t3chn0m4g3** [comment]
Thanks for reporting back.
