### ISSUE TITLE
How can we use ubuntu 16.04 full iso instead of mini iso?

### ISSUE THREAD

**Issue by masifpak** [dtag-dev-sec/t-pot-autoinstall#16]
ISO image created by using mini iso is very time taking while installation. I may be download everything from internet. Is there any way to full iso and reduce this time. I tried many times but it just jump to "burn iso on USB disk."

**Comment by t3chn0m4g3** [comment]
As a design decision we moved away from using the full installer since we are only using a small fragment of packages of it and most of the rest will be downloaded anyways; resulting in a smaller installation footprint.

**Comment by masifpak** [comment]
Apart from this, if we want this how can we do this. We are considering a scenario where we don.t have internet.

**Comment by t3chn0m4g3** [comment]
I understand. T-Pot's design heavily relies on an active internet connection, either via proxy or direct. This ensures all the necessary (security-) updates while having access to the latest available packages.
Of course you can preload images, packages and such (we have tinkered with that in the [16.03](https://github.com/dtag-dev-sec/tpotce/blob/16.03)) but decided against it. Within the branch you can find  `makeiso.sh` which still contains all information needed to use the full ISO.

**Comment by masifpak** [comment]
Actually I copied ubuntu full iso in tpotce directory and rename it to mini.iso to not disturb flow of script. Script run in same pattern but when it prompt "

> mount: block device /home/itsec/tpotce/mini.iso is write-protected, mounting read-only"

, it do not change any block and just switch to 

> "Write .iso to USB drive"

It bypass below steps altogether.

> 182338 blocks
> 182747 blocks
>  T-Pot - ISO Creator

**Comment by t3chn0m4g3** [comment]
Will not work, since `mini.iso` has a completely different file structure.

Please have a look at the code from [16.03, makeiso.sh](https://github.com/dtag-dev-sec/tpotce/blob/16.03).

Please understand that we moved away from the full iso for a good reason.
