### ISSUE TITLE
Blank screen after auto install on ubuntu 16.04 vps

### ISSUE THREAD

**Issue by DataDrug** [dtag-dev-sec/t-pot-autoinstall#17]
![blankscreen](https://cloud.githubusercontent.com/assets/17508395/26207968/df28c4e2-3be0-11e7-8fed-a7d6d8fa18ef.png)

This is what I see after the instalation is finished (tried vps reboot)

Any ideas ?

**Comment by t3chn0m4g3** [comment]
Containers not started. Please run `dps.sh` and post the output.

**Comment by DataDrug** [comment]
figured it out.

By the way, I'm already seeing some events on the honeypots, how do I see what kind of malware I'm receiving ?

**Comment by t3chn0m4g3** [comment]
Either through the dashboards or in `/data`.

**Comment by t3chn0m4g3** [comment]
I assume, I can close this?

**Comment by DataDrug** [comment]
Yes sure. I'm able to access data via ssh, but haven't figured out how to see malware hashes on the webpage.

**Comment by t3chn0m4g3** [comment]
This depends on the honeypot. Go to `discover` load i.e. `honeytrap`logs and you should the hashes.
![image](https://cloud.githubusercontent.com/assets/4318452/26255414/ce5f8446-3cb9-11e7-935d-a7ca783386ed.png)

**Comment by DataDrug** [comment]
You are the man, thanks!
