### ISSUE TITLE
Setting up t-pot on google cloud platform

### ISSUE THREAD

**Issue by abhinavbom** [dtag-dev-sec/t-pot-autoinstall#2]
Hi Team,
I signed up for a free trial of Google cloud platform with ubuntu 14 and 40 GB hardisk space. 
I used the installer script to set up t-pot on it. 
The installation completed successfully but I am not sure how to proceed next. 
I am fairly new to docker so I am not sure how to begin my honypot instances, how to check if they are running fine and check the logs they are generating. 
Can you help me in this regard.

**Comment by vorband** [comment]
Pease have  a look here
http://dtag-dev-sec.github.io/mediator/feature/2015/03/17/concept.html
