### ISSUE TITLE
/usr/share/dict/names doesn't exist on ubuntu 16.04?

### ISSUE THREAD

**Issue by ctindel** [dtag-dev-sec/t-pot-autoinstall#20]
I ran into an issue where the remote name generator wasn't accessible, but this file doesn't exist on ubuntu either:

https://github.com/dtag-dev-sec/t-pot-autoinstall/blob/8bc9d441f08388334759507bdda28339227650d3/install.sh#L24

I tried installing the wamerican package but that only installs /usr/share/dict/words.  

Is it really necessary to change the hostname in the first place?  If so I think you'll need to find another names file.

Also I think www.nsanamegenerator.com is gone now so you'll probably want to update this to use something else?

**Comment by xchen0731** [comment]
I have the same issue. 

root@honeypot:/home/notused/t-pot-autoinstall# $(curl -s -f www.nsanamegenerator   .com | html2text | tr A-Z a-z | awk     '{print $1}')
root@honeypot:/home/notused/t-pot-autoinstall# echo $myHOST

root@honeypot:/home/notused/t-pot-autoinstall# ping www.nsanamegenerator.com
PING www.nsanamegenerator.com (69.64.147.242) 56(84) bytes of data.
64 bytes from rc.hotkeys.com (69.64.147.242): icmp_seq=1 ttl=237 time=132 ms
64 bytes from rc.hotkeys.com (69.64.147.242): icmp_seq=2 ttl=237 time=132 ms

**Comment by vorband** [comment]
fixed in latest commit

**Comment by xchen0731** [comment]
Thank you ! 
Since I have already tried to install the auto-install, the script is not happy to re-execute it even by deleting the install.log. Any idea how can I reset the auto-install from scratch ?

**Comment by ctindel** [comment]
I usually just tear down the VM and install a new one each time. I have an expect script that runs the installer since they don't provide a way to supply all the answers in a config file.

**Comment by xchen0731** [comment]
Yeah ... that's what I do as well. I just wanted to save some time. :)
Many thanks !
