### ISSUE TITLE
Script Stops

### ISSUE THREAD

**Issue by aforester** [dtag-dev-sec/t-pot-autoinstall#22]
Followed all the directions but the script just dies after I make my selection. I get presented with the menu and pick option 4. It tells me "Bring it on" line and then just exits back out to the command prompt.

**Comment by vorband** [comment]
I cannot reproduce the problem. Are you on ubuntu 16.04? are you meeting the required specs? Do you have a working internet connection?

**Comment by aforester** [comment]
Apparently, the issue was caused by my SSH client. Moved to putty and it works fine.
