### ISSUE TITLE
Installer doesn't recognize ~/.ssh/authorized_keys2

### ISSUE THREAD

**Issue by musevg** [dtag-dev-sec/t-pot-autoinstall#25]
Hi there,

I just have a small glitch to report:
The standard Xenial install at my provider (Kimsufi/OVH) puts ssh keys into ~/.ssh/authorized_keys2 
which works fine for normal ssh login, but not for the autoinstall script: It fails with the message
```
Checking prerequisites...
### No SSH key for user 'spx' found in /home/spx/.ssh/authorized_keys.\n ### Script will abort!

```
I know it's easy to work around this via e.g. `ln,` but maybe you want to take care of this glitch.

Thanks,
M

**Comment by vorband** [comment]
Thank you for your report. However, we consider this to be a "non standard issue". 
Standard Ubuntu keeps the authorized keys  it at /etc/ssh/%u/authorized_keys.

But hey, you already know your workaround. :)
