### ISSUE TITLE
Honeypot Real Time map

### ISSUE THREAD

**Issue by DataDrug** [dtag-dev-sec/t-pot-autoinstall#28]
Hello @t3chn0m4g3,

I've been using T-POT for awhile now and it's been really usefull.

I've been wondering if there is any documentation provided on how to forward the logs in order to achive what's done here: 

http://community.sicherheitstacho.eu/start/main

Thank you for your time.

**Comment by t3chn0m4g3** [comment]
@DataDrug Log forwarding has been discussed [here](https://github.com/dtag-dev-sec/tpotce/issues/79). Basically you have to tell logstash to send logs to a different receiver.

**Comment by vorband** [comment]
you can now run our [open source backend](https://github.com/dtag-dev-sec/PEBA) yourself and submit your data from your t-pot installations to your own backend. 
You can then use the APIs provided by PEBA to create something like sicherheitstacho.eu yourself. 

However, we do not plan to publish the frontend map as open source.
