### ISSUE TITLE
Autoinstall for 17.10?

### ISSUE THREAD

**Issue by mattmac1** [dtag-dev-sec/t-pot-autoinstall#30]
Hi there,
Just wondering if you are planning doing an autoinstall for 17.10? I host the old version on EC2 but need to do a reinstall so was wondering if I should wait and install new version?

Never tried install from an ISO on ec2 so this makes my life a lot easier :-) 

Thanks,
Matt

**Comment by vorband** [comment]
yes, we plan on doing so. But unfortunately, no timeframe yet...

**Comment by mattmac1** [comment]
No worries I understand you guys are busy :-) thanks!

**Comment by vorband** [comment]
Thanks, I hope it will only be a matter of a couple of days/few weeks.
