### ISSUE TITLE
Unable to login via SSH / Web

### ISSUE THREAD

**Issue by zTemplar85** [dtag-dev-sec/t-pot-autoinstall#33]
Hi,

I got locked out of my honeypot completely, unable to access via SSH / Web.
I try rebuilding, script ran fine. But the same issue happen once the script rebooted, got completely lock out again.

Based on my testing, upon reboot of the machine, I have a few minutes that allow me to ssh in, but after awhile I get cut off.

**Comment by vorband** [comment]
we cannot reproduce this.
