### ISSUE TITLE
I don't know the username and password

### ISSUE THREAD

**Issue by weiyuchen** [dtag-dev-sec/t-pot-autoinstall#37]
hello, I'm using your autoinstall in my server and it works in web and I know the web username and passwd,  but I can't enter the backward t-pot system, I didn't remember that I had set the username and passwd, thank you!

**Comment by vorband** [comment]
you had to have your own ubuntu account setup before you ran t-pot-autoinstaller. The username is the same as for the web access. You can still login via ssh using the ssh key, port 64295.

**Comment by vorband** [comment]
I don't understand. _Where_ did you get this error message "Unable to connect to Elasticsearch at http://elasticsearch:9200."? Can you post a screenshot?

**Comment by weiyuchen** [comment]
![_20180328215249](https://user-images.githubusercontent.com/9763862/38033392-87b08fb2-32d2-11e8-9a1e-a51574d6f3da.png)
oh, it's so nice of you, as you can see, I can't connect the elasticsearch, and I tried to modify the elasticsearch.yml, but I found the http.host is 0.0.0.0, it's not a local url, so I don't change it

**Comment by vorband** [comment]
can you repost this issue in the corresponding repo? This does not seem to be related to the autoinstaller. 
https://github.com/dtag-dev-sec/tpotce/issues 
@t3chn0m4g3 may be able to help you.

**Comment by weiyuchen** [comment]
ok, thank you very much
