### ISSUE TITLE
Cloning T-Pot: error: RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by mullvadcat** [dtag-dev-sec/t-pot-autoinstall#39]
when use t-pot-autoinstall to install on Ubuntu 16.04.4 LTS server ,failed ,would u pls tell me how to fixed this issue? thanks
install.err shows that information ：  

  8850K .......... .......... .......... .......... .......... 98% 6.99M 0s
  8900K .......... .......... .......... .......... .......... 99%  217K 0s
  8950K .......... .......... .......... .......... .......... 99%  220K 0s
  9000K .......... .......... .......... ..                   100% 12.4M=34s

2018-04-03 20:17:31 (266 KB/s) - ‘ctop’ saved [9249384/9249384]

### Cloning T-Pot.
Cloning into '/opt/tpot'...

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by vorband** [comment]
also looks like a network problem to me...

**Comment by mullvadcat** [comment]
@vorband thank you for your reply, but when i use tpot.iso to install T-pot 17 on the same network，it is successful.  Is it possible that this problem is caused by local linux ”git config --global http.postbuffer”?

**Comment by mullvadcat** [comment]
@vorband ok i will try it again,thank you very much

**Comment by vorband** [comment]
assuming this is resolved
