### ISSUE TITLE
Question about running two tpot instance

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/t-pot-autoinstall#4]
Hello
Is it possible run two tpot instance but all data send to one ELK? or maybe remote ELK?
which file i should change for that?

**Comment by schmalle** [comment]
Dear Markus, At the moment only the 1::1 feature is supported, as the
components
e.g. directly read data,from the local file system and import it. We also
already thought
about such a feature, but it is not decided, when we we build it. In
generally you would
have to look at every comtainer and adapt code, not an easy change.
Best wishes
Markus
