### ISSUE TITLE
Facing Error While Running the script

### ISSUE THREAD

**Issue by seantree** [dtag-dev-sec/t-pot-autoinstall#40]
Hi I am facing the error while executing the script

./install.sh: 120: ./install.sh: [[: not found
cut: the delimiter must be a single character
Try 'cut --help' for more information.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
./install.sh: 150: [: !=: unexpected operator
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
./install.sh: 170: ./install.sh: Syntax error: redirection unexpected

**Comment by vorband** [comment]
sorry, we cannot reproduce this.
