### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by EsenkayShady** [dtag-dev-sec/t-pot-autoinstall#44]
Hello, How Can I be able to edit the logo to my company logo? I changed the files manually under /opt/../../elk/.. but didn't update

**Comment by t3chn0m4g3** [comment]
No, unfortunately not. Follow the [Kibana Dockerfile](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/elk/kibana/Dockerfile) and you will see that Kibana needs rebundling for change in logos to work.

**Comment by nu11secur1ty** [comment]
thank you, dear friend "t3chn0m4g3" ;)
