### ISSUE TITLE
Nginx proxy_pass for Kibana mismatched slash

### ISSUE THREAD

**Issue by xxdesmus** [dtag-dev-sec/t-pot-autoinstall#45]
In the nginx conf you have:

     ### Kibana
    location /kibana/ {
        proxy_pass http://localhost:64296;
        rewrite /kibana/(.*)$ /$1 break;
     }

but in the `tpotweb.html` file you reference `/kibana` so the proxy_pass doesn't match ...and you end up with the port # in the URL.

Related files:
`/etc/nginx/sites-enabled/tpotweb.conf`  -- has /kibana/
`/usr/share/nginx/html/tpotweb.html` -- has /kibana
`/usr/share/nginx/html/navbar.html` -- has /kibana

These should match. Happy to send a PR if helpful, just let me know.

**Comment by t3chn0m4g3** [comment]
Thank you for reporting, but why do you think the `proxy_pass` does not match? Please bare in mind, that this is just a rule for a URI `location` and as such requests are just forwarded to the upstream server while the rewrite rule only takes care of the URI `location`.

**Comment by xxdesmus** [comment]
Hi,

At least in the case of my setup from roughly a week ago (with code from that day) the link for Kibana was broken and was not matching the `proxy_pass`. 

I had my stuff setup to resolve to https://tpot.DOMAIN/  ...and the top bar/banner on the main landing homepage pointed at `https://tpot.DOMAIN:64296/kibana/`  because of the missing / in `tpotweb.html` and `navbar.html`

I updated `/usr/share/nginx/html/tpotweb.html` and `/usr/share/nginx/html/navbar.html` to then  use `/kibana/` and the broken links then correctly used `https://tpot.DOMAIN/kibana/` 

Maybe this is just something weird with my setup though.

**Comment by t3chn0m4g3** [comment]
Strange, this setup works fine and mostly unchanged since T-Pot 16.10.

Usually you call `https://your.ip:64297`. From your description it looks like you are using `:443`.

I am reluctant to make changes to the rewrite rules since this is the first time someone reported an error. However will keep an eye on it since a change would be fairly simple.

Your are correct on the trailing `/` this is indeed inconsistent and will be changed for 18.10.

**Comment by xxdesmus** [comment]
I'll see if I can duplicate how I'm causing this. I am fronting this setup through Cloudflare (so another reverse proxy) and serving it over 443/HTTPS -- so maybe the additional reverse proxy nad causing the issue.

Looking forward  to 18.10. Thanks!

**Comment by t3chn0m4g3** [comment]
@xxdesmus Any luck on how the issue is caused?

**Comment by xxdesmus** [comment]
Sadly no. I haven’t been able to replicate it yet.
