### ISSUE TITLE
Recommended servers

### ISSUE THREAD

**Issue by cheo2322** [dtag-dev-sec/t-pot-autoinstall#47]
Hi everyone,

What server (Google, AWS, Azure, ...) do you recommend to me for mounting T-Pot 17.10?

**Comment by t3chn0m4g3** [comment]
As long as it supports Ubuntu Server 16.04 LTS you are good to go.

**Comment by cheo2322** [comment]
Thank you but I would like to have answers based on experience. For example, some servers have DDoS attacks protection, it will affect our honeypot behavior, will not? I will be testing it on the next days and will write here my experience. Then, I will close this issue.

**Comment by t3chn0m4g3** [comment]
DDoS protection will not affect how the honeypot works.

**Comment by cheo2322** [comment]
Thanks for your answer, Sir. It will be very useful to me. Closing...
