### ISSUE TITLE
Migrating

### ISSUE THREAD

**Issue by roo7break** [dtag-dev-sec/t-pot-autoinstall#5]
Hi,

I would like to rebuild my t-pot instance but want to keep all the analysed data. Can you guide me to migrate from current instance to a fresh new instance?

**Comment by t3chn0m4g3** [comment]
What version are you on? 16.03 or 15.03? If you are unsure do you have a Cowrie (16.03) or a Kippo Container (15.03)?

**Comment by roo7break** [comment]
The latest - 16.03

**Comment by t3chn0m4g3** [comment]
T-Pot 16.03 is shipping with a backup script `backup_elk.sh` which needs to run as root. However it will only backup `/data/elk` as base (only config) and all with data (elastic db). If you want to keep the container data you need to do that manually.

There is no restore script (yet), you have to disable the following cronjob in `/etc/crontab`:
```
# Check if containers and services are up
*/5 * * * *   root 	check.sh
```
and manually untar (as root) the all file and make sure to set the correct permissions:
```
tar xvfz elkall.tgz -C /
chmod 760 -R /data/elk
chown tpot:tpot -R /data/elk
```

**Comment by roo7break** [comment]
Does the cronjob delete and reload the containers every night? So by creating a new instance and manually pushing old elk into new, should "migrate" all the info right?

**Comment by t3chn0m4g3** [comment]
You disable the cronjob with a `#` at the beginning of the line to ensure the check script does not interfere with your restore operation. Same goes for stopping the docker service.
To see if the data restores as expected I recommend to setup a VM first and check if everything restored to your liking. Please be reminded the backup script takes only care of the ELK data and nothing else.
