### ISSUE TITLE
Install script not working in Ubuntu 16.04 in AWS

### ISSUE THREAD

**Issue by racompton** [dtag-dev-sec/t-pot-autoinstall#51]
I spun up the “Ubuntu Server 16.04 LTS (HVM), SSD Volume Type” AMI in AWS and selected t2.large. I ssh'ed in and did a “sudo apt update ; sudo apt upgrade -y”. I then cloned the git repository and did a “sudo su” and then ran “./install.sh”. I selected user “ubuntu” and then selected option #1. The script then quit. No error message or anything. Any idea what the issue is?

**Comment by racompton** [comment]
ubuntu@ip-172-31-2-52:~$ cd t-pot-autoinstall/
ubuntu@ip-172-31-2-52:~/t-pot-autoinstall$ sudo su
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall# ./install.sh


##########################################################
# T-Pot 17.10 install script                             #
# for Ubuntu server 16.04.0x, x64                        #
##########################################################
Make sure the key-based SSH login for your normal user is working!

Which user do you usually work with?
This script is invoked by root, but what is your normal username?
Enter username: ubuntu

Checking prerequisites...
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
Everything looks OK...
##########################################################
#                                                        #
#     How do you want to proceed? Enter your choice.     #
#                                                        #
#     Required: 4GB RAM, 64GB disk                       #
#     Recommended: 8GB RAM, 128GB SSD                    #
#                                                        #
# 1 - T-Pot's STANDARD INSTALLATION                      #
#     Standard Honeypots, Suricata & ELK                 #
#                                                        #
# 2 - T-Pot's HONEYPOTS ONLY                             #
#     Honeypots only, w/o Suricata & ELK                 #
#                                                        #
# 3 - T-Pot's INDUSTRIAL EDITION                         #
#     Conpot, eMobility, Suricata & ELK                  #
#                                                        #
# 4 - T-Pot's FULL INSTALLATION                          #
#     Everything                                         #
#                                                        #
##########################################################

Your choice: 4
You chose to install T-Pot's FULL INSTALLATION. Bring it on...
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall# ls
install.err  install.log  install.sh  LICENSE  README.md
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall# less install.err 
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall# less install.log 
Everything looks OK...

ESC[HESC[J##########################################################
#                                                        #
#     How do you want to proceed? Enter your choice.     #
#                                                        #
#     Required: 4GB RAM, 64GB disk                       #
#     Recommended: 8GB RAM, 128GB SSD                    #
#                                                        #
# 1 - T-Pot's STANDARD INSTALLATION                      #
#     Standard Honeypots, Suricata & ELK                 #
#                                                        #
# 2 - T-Pot's HONEYPOTS ONLY                             #
#     Honeypots only, w/o Suricata & ELK                 #
#                                                        #
# 3 - T-Pot's INDUSTRIAL EDITION                         #
#     Conpot, eMobility, Suricata & ELK                  #
#                                                        #
# 4 - T-Pot's FULL INSTALLATION                          #
#     Everything                                         #
#                                                        #
##########################################################

Your choice: You chose to install T-Pot's FULL INSTALLATION. Bring it on...
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall# uname -a
Linux ip-172-31-2-52 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-31-2-52:/home/ubuntu/t-pot-autoinstall#

**Comment by racompton** [comment]
it looks like your "fuECHO" function was failing.  I commented out:
#local myRED=1
#local myWHT=7
#tput setaf $myRED
#tput setaf $myWHT
and now it seems to run fine.  I'm using SecureCRT.  Maybe that has something to do with it.

**Comment by vorband** [comment]
Glad you found a workaround.
