### ISSUE TITLE
Is there a way to have a honeypot send events to a remote console?

### ISSUE THREAD

**Issue by racompton** [dtag-dev-sec/t-pot-autoinstall#52]
Hi, I'd like to select option for just installing the honeypots and having the logs for the honeypots send events to a remote t-pot server running "everything".  Is that possible?  What configuration would I need to add?  It would be great if this was an option in the install menu.  Numerous honeypots located at various points around a network could then all report their logs to the centralized ELK instance.

**Comment by vorband** [comment]
so far, there is no out of the box setup for this. But please have a look at the main [tpotce](https://github.com/dtag-dev-sec/tpotce/) repository. Similar topics have been discussed in the issues.
