### ISSUE TITLE
Ansible Playbook Suggestion

### ISSUE THREAD

**Issue by jaredestroud** [dtag-dev-sec/t-pot-autoinstall#6]
Hello,

I recently modified the t-pot-autoinstall bash script to take command line options for deployment. This way I could integrate it into an Ansible playbook for easy deployment on remote a VPS. 

Is this something you would be interested in merging into the project? Maybe have a separate branch for Ansible deployments?

Thank you for your time.

**Comment by vorband** [comment]
sure. we're open to new ideas. anywhere I could get a peek?

**Comment by jaredestroud** [comment]
Absolutely.
[Here](https://github.com/jaredestroud/t-pot-autoinstall/blob/master/tpot_deploy.yml) is the Ansible playbook.
The modified script is [here](https://github.com/jaredestroud/t-pot-autoinstall/blob/master/install.sh), and I've updated the README in my repo with instructions on how to run [here](https://github.com/jaredestroud/t-pot-autoinstall/blob/master/README.md).

**Comment by smtszk** [comment]
Ansible would be great for T-pot. Deployment can be very easy by using ansible.

**Comment by vorband** [comment]
although not ansible, we now support non-interactive installs in our latest release for T-Pot 17.10.
